kind: Deployment
apiVersion: apps/v1
metadata:
    labels:
        app: cw-microservice
        stack: frontend
        source: demo
    name: cw-microservice
    namespace: microservices
spec:
    replicas: 3
    selector:
        matchLabels:
            run: cw-microservice
    template:
        metadata:
            labels:
                app: cw-microservice
                run: cw-microservice
                source: demo
        spec:
            containers:
                - image: 219099013464.dkr.ecr.us-west-2.amazonaws.com/cw-microservice
                  name: cw-microservice
                  ports:
                      - name: web
                        containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
    labels:
        app: cw-microservice-service
    name: cw-microservice-service
    namespace: microservices
spec:
    selector:
        source: demo
        app: cw-microservice
    ports:
        - name: web
          protocol: TCP
          port: 30201
          targetPort: 8080

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$2
    name: cw-ingress
    namespace: microservices
spec:
    rules:
        - http:
              paths:
                  - path: /cw(/|$)(.*)
                    backend:
                        serviceName: cw-microservice-service
                        servicePort: 30201
